import { requireUser } from '@/lib/auth';
import { redirect } from 'next/navigation';
import { hodStats,hodDemand,facultySubmission,settings,generateSampleAllotments,courseGroupDemand } from '@/lib/store';
function fmtRanks(rc:any){return <div className="rankgrid hodranks">{[1,2,3,4,5,6].map(n=><span key={n} className={(rc?.['p'+n]||0)?'rank on':'rank'}><b>P{n}</b><em>{rc?.['p'+n]||0}</em></span>)}<span className="rank total"><b>Total</b><em>{rc?.total||0}</em></span></div>}
function fmtDate(s?:string){if(!s)return '—'; const d=new Date(s); if(isNaN(d.getTime()))return s; return d.toLocaleDateString('en-GB').replaceAll('/','-')}
export default async function HoD({searchParams}:{searchParams:Promise<any>}){
 const u=await requireUser('HoD'); if(!u) redirect('/login'); const sp=await searchParams; const tab=String(sp?.tab||'courses'); const st=await hodStats(), demand=await hodDemand(), groups=await courseGroupDemand(), subs=await facultySubmission(), sets=await settings(), opts=await generateSampleAllotments(); const submitted=subs.filter((f:any)=>f.cnt>0).length;
 return <><nav><b>HoD Dashboard</b><span></span><a href="/faculty">Faculty View</a><a href="/hod/strategy">HoD Strategy</a><a href="/admin">Admin</a><a href="/api/logout">Logout</a></nav><main><h1>{sets.department_name||'Department'} — {sets.academic_year} {sets.term} Theory Allotment</h1><div className="banner">Preference window: <b>{sets.preference_status}</b> &nbsp; Opens: <b>{fmtDate(sets.preference_start_date)}</b> &nbsp; Closes: <b>{fmtDate(sets.preference_close_date)}</b></div><div className="cards"><div><b>{st.offerings}</b><br/>Course offerings</div><div><b>{st.theory}</b><br/>Theory offerings</div><div><b>{st.courseUnits}</b><br/>Grouped course units</div><div><b>{st.submitted}/{st.faculty}</b><br/>Faculty submitted</div><div><b>{st.prefs}</b><br/>Total preferences</div></div>
 <div className="tabs"><a className={tab==='courses'?'active':''} href="/hod?tab=courses">1. Course Demand</a><a className={tab==='groups'?'active':''} href="/hod?tab=groups">2. Course Group Demand</a><a className={tab==='faculty'?'active':''} href="/hod?tab=faculty">3. Faculty Preferences</a><a className={tab==='allot'?'active':''} href="/hod?tab=allot">4. Allotment Actions</a></div>
 {tab==='courses'&&<section><h2>Course Demand</h2><table><thead><tr><th>Course</th><th>Inst</th><th>Sem</th><th>Sections</th><th>Credits</th><th>L-T-P</th><th>Hrs/Wk</th><th>Needed</th><th>Course Competition</th></tr></thead><tbody>{demand.map((c:any)=><tr key={c.course_key}><td><b>{c.course_code}</b><br/>{c.course_name}<br/><span className="muted">{c.course_group}</span></td><td>{c.institution}</td><td>{c.semester}</td><td>{c.sections.join(', ')}</td><td>{c.credits||c.hours_per_week}</td><td>{c.l}-{c.t}-{c.p}</td><td>{c.hours_per_week}</td><td>{c.needed}</td><td>{fmtRanks(c.rankCounts)}</td></tr>)}</tbody></table></section>}
 {tab==='groups'&&<section><h2>Course Group Demand</h2><table><thead><tr><th>Group</th><th>GMU Courses</th><th>GMIT Courses</th><th>Total Needed</th><th>Group Competition</th></tr></thead><tbody>{groups.map((g:any)=><tr key={g.group}><td><b>{g.group}</b></td><td>{g.gmu.join(', ')||'—'}</td><td>{g.gmit.join(', ')||'—'}</td><td>{g.needed}</td><td>{fmtRanks(g.rankCounts)}</td></tr>)}</tbody></table></section>}
 {tab==='faculty'&&<section><h2>Faculty Preferences</h2><p className="muted">All: {subs.length} | Submitted: {submitted} | Not submitted: {subs.length-submitted}</p><p><a className="btn" href="/api/hod/export-faculty-preferences">Export Faculty Preferences CSV</a></p><table><thead><tr><th>Faculty</th><th>Designation</th><th>Experience</th><th>Status</th><th>No.</th><th>Total Hrs</th><th>Preferences Ordered</th><th>Teaching Intent</th></tr></thead><tbody>{subs.map((f:any)=><tr key={f.faculty_id}><td>{f.faculty_name}<br/><span className="muted">{f.user_id}</span></td><td>{f.designation}<br/><span className="muted">{f.seniority_level}</span></td><td>{f.years_experience||0}</td><td><span className={f.cnt?'status submitted':'status pending'}>{f.status}</span></td><td>{f.cnt}</td><td>{f.load}</td><td>{f.prefRows?.map((p:any)=><div key={p.preference_id}><b>P{p.preference_rank}</b>: {p.course_code} — {p.course_name}</div>)}</td><td>{f.prefRows?.map((p:any)=><details key={p.preference_id}><summary>P{p.preference_rank}: {p.course_code}</summary><div className="intent">{p.teaching_intent||'—'}</div></details>)}</td></tr>)}</tbody></table></section>}
 {tab==='allot'&&<section><h2>Allotment Actions</h2><p className="muted">Draft suggestions only. Four methods are shown below; HoD may edit before freezing final allotment.</p><div className="actionbar"><a className="btn" href="#preference">Preference Priority</a><a className="btn" href="#workload">Workload Balanced</a><a className="btn" href="#coverage">Course Coverage First</a><a className="btn" href="#experience">Experience Balanced</a><a className="btn" href="#strategic">HoD Strategic</a></div><div className="option-grid">{opts.map((o:any)=>{const title:any={preference:'Preference Priority',workload:'Workload Balanced',coverage:'Course Coverage First',experience:'Experience Balanced',strategic:'HoD Strategic'};return <div className="option" id={o.strategy} key={o.strategy}><h3>{title[o.strategy]}</h3><p><b>P1:</b> {o.summary.p1} &nbsp; <b>P2/P3:</b> {o.summary.p23} &nbsp; <b>Uncovered:</b> {o.summary.uncovered}<br/><b>Avg load:</b> {o.summary.avg} &nbsp; <b>Max load:</b> {o.summary.max}</p><p className="muted">Semester experience: {o.semExperience?.map((x:any)=>`Sem ${x.sem}: ${x.avg} yrs`).join(' | ')||'—'}</p><table><thead><tr><th>Faculty</th><th>Exp</th><th>Course</th><th>Pref</th><th>Hrs</th><th>Inst/Sem/Sections</th></tr></thead><tbody>{o.assigned.map((a:any,i:number)=><tr key={i}><td>{a.faculty_name}</td><td>{a.years_experience}</td><td>{a.course_code}<br/><span className="muted">{a.course_name}</span></td><td>P{a.preference_rank}</td><td>{a.hours}</td><td>{a.institution}/{a.semester}/{a.sections.join(', ')}</td></tr>)}</tbody></table></div>})}</div></section>}
 </main></>}
